/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2025-04-30 11:07:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cargo.*;
import java.sql.*;

public final class viewallusers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Logistica Bookings </title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Roboto:wght@500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-grow text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n");
      out.write("            <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-white navbar-light shadow border-top border-5 border-primary sticky-top p-0\">\r\n");
      out.write("        <a href=\"index.html\" class=\"navbar-brand bg-primary d-flex align-items-center px-4 px-lg-5\">\r\n");
      out.write("            <h2 class=\"mb-2 text-white\">Logistica</h2>\r\n");
      out.write("        </a>\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggler me-4\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("            <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("                <a href=\"usermain.html\" class=\"nav-item nav-link \">Booking</a>\r\n");
      out.write("                <a href=\"admin.html\" class=\"nav-item nav-link\">View Location</a>\r\n");
      out.write("                 <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link active dropdown-toggle\" data-bs-toggle=\"dropdown\">View</a>\r\n");
      out.write("                    <div class=\"dropdown-menu fade-up m-0\">\r\n");
      out.write("                        <a href=\"viewCargo.jsp\" class=\"dropdown-item\">View Cargo</a>\r\n");
      out.write("                        <a href=\"viewallusers.jsp\" class=\"dropdown-item\">View all Users</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"userlogin.html\" class=\"nav-item nav-link\">Login</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h4 class=\"m-0 pe-lg-5 d-none d-lg-block\"><i class=\"fa fa-headphones text-primary me-3\"></i>+91 9881678837</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Page Header Start -->\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"container-fluid page-header py-5\" style=\"margin-bottom: 6rem;\">\r\n");
      out.write("    <div class=\"container py-5\">\r\n");
      out.write("        <h1 class=\"display-3 text-white mb-3 animated slideInDown\">Logistica</h1>\r\n");
      out.write("        <nav aria-label=\"breadcrumb animated slideInDown\">\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("                <h5 style=\"color: azure;\">Cargo Transport</h5>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Page Header End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Quote Start -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container py-5\">\r\n");
      out.write("        <p style=\"text-align: center; font-size: 50px;\">View All Users </p>\r\n");
      out.write("        <div style=\"align-items: center; padding-left:5cm; padding-right: 5cm;\" >\r\n");
      out.write("            <div class=\"bg-light text-center p-5 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                  \r\n");
      out.write("          \t\t");

		        	
        		
      out.write("\r\n");
      out.write("                  <table style=\"width:100%\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th>Name</th>\r\n");
      out.write("                      <th>Company Name</th>\r\n");
      out.write("                      <th>User Email</th>\r\n");
      out.write("                      <th>Mobile No </th>\r\n");
      out.write("                      <th>Address </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                ");

                	Connection con = ConnectDB.connect();
               		 try
               		 {
			        	PreparedStatement ps = con.prepareStatement("SELECT * FROM user_tbl");
			        	ResultSet rs = ps.executeQuery();
        				while(rs.next())
        				{
       			
      out.write("\r\n");
      out.write("\t\t\t\t  \t\t\t <tr>\r\n");
      out.write("\t\t\t\t\t\t\t    <td>");
      out.print(rs.getString("user_name"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t    <td>");
      out.print(rs.getString("user_company"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t    <td>");
      out.print(rs.getString("user_email"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t    <td>");
      out.print(rs.getString("user_mobile"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t    <td>");
      out.print(rs.getString("user_address"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t  ");

			  		}
			  	}
			  	catch(Exception e)
			  	{
			  		e.printStackTrace();
			  	}
			  
			  
      out.write("\r\n");
      out.write("\t\t\t  \r\n");
      out.write("                  </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Quote End -->\r\n");
      out.write("    <!-- Service Start -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"text-center wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                <h6 class=\"text-secondary text-uppercase\">Our Services</h6>\r\n");
      out.write("                <h1 class=\"mb-5\">Explore Our Services</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row g-4\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"service-item p-4\">\r\n");
      out.write("                        <div class=\"overflow-hidden mb-4\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/service-1.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"mb-3\">Air Freight</h4>\r\n");
      out.write("                        <p>We provide fast and reliable air freight services for time-sensitive shipments. Leveraging our network of airline partners and industry expertise, we offer efficient routing, competitive rates, and real-time tracking for your air cargo needs.</p>\r\n");
      out.write("                        <a class=\"btn-slide mt-2\" href=\"\"><i class=\"fa fa-arrow-right\"></i><span>Read More</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"service-item p-4\">\r\n");
      out.write("                        <div class=\"overflow-hidden mb-4\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/service-2.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"mb-3\">Ocean Freight</h4>\r\n");
      out.write("                        <p>Our ocean freight services cater to the transportation of large volumes of cargo across international waters. We offer both full container load (FCL) and less than container load (LCL) options, ensuring cost-effective and efficient shipping solutions</p>\r\n");
      out.write("                        <a class=\"btn-slide mt-2\" href=\"\"><i class=\"fa fa-arrow-right\"></i><span>Read More</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <div class=\"service-item p-4\">\r\n");
      out.write("                        <div class=\"overflow-hidden mb-4\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/service-3.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"mb-3\">Road Freight</h4>\r\n");
      out.write("                        <p>We have a strong road transport network that allows us to provide domestic and cross-border transportation services. Whether it's a small parcel or a full truckload, we offer reliable and secure road transport solutions to deliver your cargo to its destination.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a class=\"btn-slide mt-2\" href=\"\"><i class=\"fa fa-arrow-right\"></i><span>Read More</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"service-item p-4\">\r\n");
      out.write("                        <div class=\"overflow-hidden mb-4\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/service-4.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"mb-3\">Train Freight</h4>\r\n");
      out.write("                        <p>Our rail freight services offer an eco-friendly and efficient alternative for transporting cargo overland. We have partnerships with major rail operators, enabling us to offer cost-effective and sustainable transportation solutions for both domestic and international shipments.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a class=\"btn-slide mt-2\" href=\"\"><i class=\"fa fa-arrow-right\"></i><span>Read More</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"service-item p-4\">\r\n");
      out.write("                        <div class=\"overflow-hidden mb-4\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/service-5.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"mb-3\">Customs Clearance</h4>\r\n");
      out.write("                        <p>We have a dedicated team of customs experts who handle all aspects of customs clearance. They ensure compliance with regulations, manage documentation, and facilitate smooth customs processes, minimizing delays and ensuring your cargo reaches its destination on time.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a class=\"btn-slide mt-2\" href=\"\"><i class=\"fa fa-arrow-right\"></i><span>Read More</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <div class=\"service-item p-4\">\r\n");
      out.write("                        <div class=\"overflow-hidden mb-4\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"img/service-6.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"mb-3\">Warehouse Solutions</h4>\r\n");
      out.write("                        <p>We provide secure warehousing facilities for short-term or long-term storage of your cargo. Our distribution services include inventory management, order fulfillment, and last-mile delivery, ensuring efficient and timely distribution of your goods.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        <a class=\"btn-slide mt-2\" href=\"\"><i class=\"fa fa-arrow-right\"></i><span>Read More</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Service End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Feature Start -->\r\n");
      out.write("    <div class=\"container-fluid overflow-hidden py-5 px-lg-0\">\r\n");
      out.write("        <div class=\"container feature py-5 px-lg-0\">\r\n");
      out.write("            <div class=\"row g-5 mx-lg-0\">\r\n");
      out.write("                <div class=\"col-lg-6 feature-text wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <h6 class=\"text-secondary text-uppercase mb-3\">Our Features</h6>\r\n");
      out.write("                    <h1 class=\"mb-5\">We Are Trusted Logistics Company Since 1990</h1>\r\n");
      out.write("                    <div class=\"d-flex mb-5 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                        <i class=\"fa fa-globe text-primary fa-3x flex-shrink-0\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h5>Worldwide Service</h5>\r\n");
      out.write("                            <p class=\"mb-0\">Diam dolor ipsum sit amet eos erat ipsum lorem sed stet lorem sit clita duo justo magna erat amet</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex mb-5 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                        <i class=\"fa fa-shipping-fast text-primary fa-3x flex-shrink-0\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h5>On Time Delivery</h5>\r\n");
      out.write("                            <p class=\"mb-0\">Diam dolor ipsum sit amet eos erat ipsum lorem sed stet lorem sit clita duo justo magna erat amet</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex mb-0 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                        <i class=\"fa fa-headphones text-primary fa-3x flex-shrink-0\"></i>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                            <h5>24/7 Telephone Support</h5>\r\n");
      out.write("                            <p class=\"mb-0\">Diam dolor ipsum sit amet eos erat ipsum lorem sed stet lorem sit clita duo justo magna erat amet</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 pe-lg-0 wow fadeInRight\" data-wow-delay=\"0.1s\" style=\"min-height: 400px;\">\r\n");
      out.write("                    <div class=\"position-relative h-100\">\r\n");
      out.write("                        <img class=\"position-absolute img-fluid w-100 h-100\" src=\"img/feature.jpg\" style=\"object-fit: cover;\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Feature End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square rounded-0 back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
